name: Publish to npm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push version bump back to GitHub
      id-token: write # Required for provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required if pushing commits back
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

#      - name: Patch version
#        run: npm version patch -m "chore(release) %s"

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump
        run: git push origin main --follow-tags
